server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: zuul9527.com
      prefer-ip-address: true


info:
  app.name: lau-springcloud
  company.name: codinglau.top

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept  #不能在使用该路径访问:http://www.laustudy.com:9527/springcloud-provider-dept/dept/list
  prefix: /lau   #请求前面添加前缀：http://www.laustudy.com:9527/lau/mydept/dept/list
#  ignored-services: "*"   #隐藏全部